### ISSUE TITLE
different granularity of client models

### ISSUE THREAD

**Issue by KamiPan0601** [DensoITLab/Fed3DGS#3]
Thanks for your job. I'd like to ask if different clients can train their models with different levels of granularity? (e.g. different resolution, sampling density between coarse and fine models) Are there any relevant details in the paper?

**Comment by perrying** [comment]
We did not conduct experiments involving models trained with different levels of granularity (i.e., data heterogeneity), but it is an important direction for 3D reconstruction with federated learning.

**Comment by KamiPan0601** [comment]
Hi, I have another question when training global model using `python gaussian-splatting/build_global_model.py -w -o global-models/building -m local-models/building -i image-lists/building -data datasets/building-pixsfm` with the mill 19 building dataset. I got an error when I ran the above command:
```python
[05/25 23:57:15] build-global INFO: load metadata
100%  |  1940/1940 [00:00<00:00, 14448.97it/s]
[05/25 23:57:15] build-global INFO: load image lists
[05/25 23:57:15] build-global INFO: initialize global model

Traceback (most recent call last):
  File "gaussian-splatting/build_global_model.py", line 398, in <module>
    main(args)
  File "gaussian-splatting/build_global_model.py", line 292, in main
    global_model.load_ply(seed_model_file)
  File "/Fed3DGS/gaussian-splatting/scene/gaussian_model.py", line 381, in load_ply
    assert len(extra_f_names)==3*(self.max_sh_degree + 1) ** 2 - 3
AssertionError
``` 
It tells that the number of `extra_f_names` is wrong. And I got the output.
```python
Expected length: 24, Actual length: 45
Extra feature names: ['f_rest_0', 'f_rest_1', 'f_rest_2', 'f_rest_3', 'f_rest_4', 'f_rest_5', 'f_rest_6', 'f_rest_7', 'f_rest_8', 'f_rest_9', 'f_rest_10', 'f_rest_11', 'f_rest_12', 'f_rest_13', 'f_rest_14', 'f_rest_15', 'f_rest_16', 'f_rest_17', 'f_rest_18', 'f_rest_19', 'f_rest_20', 'f_rest_21', 'f_rest_22', 'f_rest_23', 'f_rest_24', 'f_rest_25', 'f_rest_26', 'f_rest_27', 'f_rest_28', 'f_rest_29', 'f_rest_30', 'f_rest_31', 'f_rest_32', 'f_rest_33', 'f_rest_34', 'f_rest_35', 'f_rest_36', 'f_rest_37', 'f_rest_38', 'f_rest_39', 'f_rest_40', 'f_rest_41', 'f_rest_42', 'f_rest_43', 'f_rest_44']
``` 
The same error and output occur with my own dataset. What do you suggest to do about it?

**Comment by perrying** [comment]
`--sh-degree` is set to an inconsistent value.
`--sh-degree=3` may be a correct value for your case (or train client models with `--sh-degree=2`, which is the same setting as in the paper.).

**Comment by KamiPan0601** [comment]
Thanks a lot! It's been solved.

**Comment by KamiPan0601** [comment]
Hi, what's the function of the metadata in the datasets (since the poses in the metadata are under the ground truth coordinate)? Are the images' poses in colmap-results under the ground truth coordinate? If not, how to transform them to ground truth? Thanks!

**Comment by perrying** [comment]
> Is the coordinate of the images' pose in colmap_result the same as that of the metadata?

Yes. We write camera poses in the metadata to the colmap db in `create_db.py`, and compute initial points of 3DGS by [point_triangulator](https://github.com/DensoITLab/Fed3DGS/blob/9d9ca8d5429ed3e86c284fb5406ed941642fe768/tools/triangulate_colmap.sh#L8) instead of mapper.

**Comment by KamiPan0601** [comment]
The relative positions of the local models are quite accurate. But I find that the pose matrix of the same image between metadata and sparse/0/images.txt are quite different.
e.g. metadata/001543.pt of mill 19 building
{'H': 3456, 'W': 4608, 'c2w': tensor([
        [-2.3664e-03, -7.0611e-01, -7.0810e-01, **-5.4320e-04**],
        [ 4.5118e-01,  6.3118e-01, -6.3091e-01,  **1.3091e-01**],
        [ 8.9243e-01, -3.2097e-01,  3.1709e-01, **-2.0047e-01**]]),
  'intrinsics': tensor([2981.5513, 2981.5513, 2304.0000, 1728.0000]), 'distortion': tensor([-0.0014,  0.0000,  0.0000,  0.0000])}

But its camera pose in images.txt is:
137 0.7865074983039898 0.32710231727304256 -0.48421067667925949 -0.19987508533086118 **0.11984353512525558 0.14735768735408783 -0.14577551186084747** 137 001543.jpg

We can see that their TX, TY, TZ are different. Why? (Does colmap do any further transform with the metadata pose?)

**Comment by perrying** [comment]
It is due to the difference of the coordinate system between Mega-NeRF and Colmap.
The camera extrinsic in metadata is camera-to-world, but that in database is world-to-camera.
Coordinate system is converted below:
https://github.com/DensoITLab/Fed3DGS/blob/9d9ca8d5429ed3e86c284fb5406ed941642fe768/tools/create_db.py#L67-L75

**Comment by KamiPan0601** [comment]
I get it! Thank you very much.
