### ISSUE TITLE
What is the effect of masking out half of the gt image？

### ISSUE THREAD

**Issue by Livioni** [DensoITLab/Fed3DGS#4]
Thanks for your job.
I'm wondering what’s the purpose of the following lines

```python
        if viewpoint_cam.is_val: # remove right-side pixels
            gt_image = gt_image[..., :gt_image.shape[-1]//2]
            image = image[..., :image.shape[-1]//2]
```
in
https://github.com/DensoITLab/Fed3DGS/blob/9d9ca8d5429ed3e86c284fb5406ed941642fe768/gaussian-splatting/train.py#L104C1-L106C52

**Comment by perrying** [comment]
see https://github.com/cmusatyalab/mega-nerf/issues/67#issuecomment-1613322566

**Comment by Livioni** [comment]
> see [cmusatyalab/mega-nerf#67 (comment)](https://github.com/cmusatyalab/mega-nerf/issues/67#issuecomment-1613322566)

Thanks for your reply!
